vllm_spyre/model_executor/model_loader/spyre.py, vllm_spyre/worker/spyre_worker.py
Test whether the requested model is a path or not. If not, acquire and use a cached model from huggingface.
=> allow loading models from huggingface

vllm_spyre/model_executor/model_loader/spyre.py
changes: 
- assures that indices in fms kv cache are correct for arbitrary list of active pages.
=> [FMS Wrapper] Bugfix 

README.md
changes:
- point to repository on vllm-project ([commit](https://github.com/vllm-project/vllm-spyre/commit/6d8d16764ee4e10ce15dde73a4dfdbd96f434a28)) (thanks @nikolaospapandreou for spotting this!)
- bump version from 0.7.3 to 0.8.0 ([commit](https://github.com/vllm-project/vllm-spyre/commit/8ea18a8f6658b5f49b63aec69ad761a5a6df3d3e))
Note: only merge after PR #37 has been merged.
=> [Readme] update repository and bump vLLM to 0.8.0

vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
Add warmup for continuous batching:
- Prefill two individual requests (batch size 1)
- One decode step with batch size 2
=> Implement warmup for continuous batching

.github/workflows/test-spyre.yml, pyproject.toml, uv.lock
Our tests are passing because they're importing the source directly, the actual installed `vllm_spyre` package is empty 🙃
=> :bug: actually install everything

tests/e2e/test_spyre_basic.py, tests/e2e/test_spyre_max_new_tokens.py, tests/spyre_util.py
Changes:
- Changed some prompts of the tests
- Increased the threshold for some tests
=> [CI] Updated tests to work with different versions of Spyre Card

tests/e2e/test_spyre_basic.py, tests/spyre_util.py
This is more pythonic + it allows the user to select an empty dir for `models`
=> ♻️ use pathlib for constructing model path

vllm_spyre/model_executor/model_loader/spyre.py
closes #97 
Tested on CPU (AIU testing not available until compiler supports continuous batching)
=> Support of llama 3.1 8B, granite 3.2 8B for continuous batching

vllm_spyre/v1/core/scheduler.py
Introducing a skip queue to fill up batches more optimally. 
Idea: move past request that do not fit the current batch warmup shapes. 
Previously the batch was scheduled when reaching a request that cannot be part of the current batch. Unused slots in a batch were simply wasted/padded. With this change we try to still fill those slots with subsequent request. Note that priority is preserved: e.g. the skipped requests will come first in the next batch.
=> [V1] Optimizing the static batching scheduler 

vllm_spyre/v1/worker/spyre_worker.py
delete entries in `model_runner.req_ids2left_pads` for warmup sequences
=> [CB] proper cleanup after warmup

vllm_spyre/model_executor/model_loader/spyre.py
Changes:
- removed dynamic dimensions of KV cache on request of the AIU Spyre compiler team.
Please approve asap, I will merge after a final confirmation from the team.
=> [CB] remove unnecessary marked dynamic dimensions

tests/e2e/test_spyre_warmup_shapes.py, vllm_spyre/platform.py
- Adds validation step for prompt length
- Adds a test for ^ catching invalid length
Closes #133
=> fix: Add validation and test for prompt len % 64

CODE_OF_CONDUCT.md, CONTRIBUTING.md, DCO
- DCO
- Code of Conduct (inherited from vLLM)
- Contributing readme linking to the site
=> Add OS-related docs

docs/source/user_guide/supported_models.md
Aligning with testing on spyre hardware. We'll update this soon with more details of which models have been verified to work
=> :fire: remove supported models

.github/workflows/reminder_comment.yml, docs/source/contributing/overview.md
Use `--inexact` instead to preserve the existing packages already installed?
=> 🎨 use sync with inexact instead?

README.md
Adds spyre overview, doc links, and contact to the repo's main readme.
=> [Docs] Update main README.md

docs/user_guide/supported_features.md
The calendar emoji may be confusing. So we decided to replace it.
=> [DOCS] replace calendar emoji in supported features

vllm_spyre/v1/worker/spyre_worker.py
Fix upstream main - v1 worker needed an `initialize_cache` function
=> 🐛 add initialize_cache for v1 worker

tests/e2e/test_spyre_cb.py
Add test to ensure that request lengths are validated and rejected in continuous batching mode.
=> [Test] CB rejects requests longer than max length

vllm_spyre/v1/worker/spyre_worker.py
order changed in this this PR: #284
=> [SB] fix order of warmup print

tests/scheduling_utils.py
This helps in debugging if we can see the expected value
=> 🎨 add values in test asserts

vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
From https://github.com/vllm-project/vllm-spyre/pull/312#discussion_r2240084152 there is a request for a nicer integration of batch size 1 support during warmup. Most of the code is already on main, thus this PR.
=> [CB] refactoring warmup for batch size 1

tests/spyre_util.py, tests/utils/test_upstream_compatibility.py, vllm_spyre/compat_utils.py, vllm_spyre/v1/worker/spyre_worker.py
The `NewRequestData` argument `mm_inputs` was renamed to `mm_kwargs`.
=> [Compat]: Fix renamed NewRequestData argument

.github/workflows/test.yml
refactoring test.yaml. Removing duplicated model strings. Use of for loop for downloads.
=> [GHA] 🎨 refactor test yaml

vllm_spyre/model_executor/model_loader/spyre.py
Make the logs better! 
```
DEBUG 08-26 09:58:39 [spyre.py:182] Loading model weights for model ibm-ai-platform/micro-g3.3-8b-instruct-1b-FP8
DEBUG 08-26 09:58:39 [spyre.py:183] Model config has dtype: torch.bfloat16
DEBUG 08-26 09:58:39 [spyre.py:189] Quantized model found with quantization : compressed-tensors
```
=> 🎨 reword logs for loading model weights

_local_envs_for_test.sh
Trim local envs not required anymore
=> 🔥 trim local envs not required anymore

docker/Dockerfile.amd64
=> :bug: fix image

.github/workflows/test.yml, tests/utils/test_upstream_compatibility.py, vllm_spyre/v1/worker/spyre_model_runner.py
Removes support for vllm 0.9.2
=> :fire: Remove vllm 0.9.2 support

tests/conftest.py, tests/e2e/test_spyre_cb.py
Restored test_swap_decode_programs_for_cb with 32K context
=> test: restored test_swap_decode_programs_for_cb with 32K context
