.github/workflows/test-spyre.yml, tests/conftest.py, tests/spyre_util.py, tests/test_spyre_basic.py, tests/test_spyre_embeddings.py, tests/test_spyre_max_new_tokens.py, tests/test_spyre_max_prompt_length.py, tests/test_spyre_seed.py, tests/test_spyre_tensor_parallel.py, tests/test_spyre_warmup_shapes.py
- add dynamo rest in conftest
- add common functions in utils to get test data
- allow user to pass custom model list, model dir, backend using env variables
=> added test clean up and customization

.github/workflows/codespell.yml, .github/workflows/reminder_comment.yml, .github/workflows/yapf.yml
Because of Path filtering in github actions, some PRs didn't trigger checks that are mandatory for the PR to be merged, and the check were staying the "Pending" state: see the effect description [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks).
This PRs remove the path filtering for mandatory actions, which will from now on be triggered on all the PRs.
=> Remove path filtering for PR mandatory git actions

vllm_spyre/v1/worker/spyre_worker.py
This ports the fix from #5 to the V1 worker.
I tested that this can download and run a small model from HF, on both v0 and v1. Tested with `Cheng98/llama-160m` and `JackFram/llama-160m`
=> :children_crossing: Port hf download fix to V1

.github/workflows/test-spyre.yml, Dockerfile.spyre, tests/spyre_util.py, tests/test_spyre_basic.py, tests/test_spyre_embeddings.py, tests/test_spyre_max_new_tokens.py, tests/test_spyre_max_prompt_length.py, tests/test_spyre_seed.py, tests/test_spyre_tensor_parallel.py, tests/test_spyre_warmup_shapes.py
Adding tests for V1 alongside the existing V0 tests.
-> This PR can be merged while still working on #17, #24 and #29
**Further TO DOs**
=> [V1] tests

vllm_spyre/__init__.py, vllm_spyre/model_executor/model_loader/spyre.py, vllm_spyre/platform.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
I noticed that we weren't seeing some of the `logger.warning` messages that I had put into the v1 code, because we never initialized the logging package correctly for the plugin.
This PR reconfigures the logging package on import, and copies the vllm logging config for `vllm_spyre` so that all the usual logging configurations still work. For example, `VLLM_LOGGING_LEVEL=WARNING` will turn the level down to warning for the vllm_spyre logs too. This allows users to configure logging the same way as they do with other hardware backends.
I went ahead and ported some of the prints in the v1 codepath to use logging as well. This now logs the file and line number where the logs came from, so we no longer need to maintain manual prefixes like `[SchedulerConfig]`  to denote where the log is from. …
=> :recycle: Use real logger

.github/workflows/test-spyre.yml
The v0 tests shouldn't need forking, since they clean up properly after themselves. This PR splits the pytest command into two separate runs, using `--forked` only for the v1 tests. 
This recent run took 12 minutes: https://github.com/vllm-project/vllm-spyre/actions/runs/13910223043/job/38922610694?pr=28
Let's see if this is faster without forking half the tests 🤞
=> :construction_worker: Only fork v1 tests

vllm_spyre/platform.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
This PR
- Cleans up unused kv-cache related APIs from the v1 worker
- Adds detailed docstrings about how the new kv-cache related v1 apis work
- Overrides the necessary values to copy v0's behavior of 1 block per sequence to avoid any preemption, prefix caching, or other kv cache block related logic in the scheduler
- Does a small refactor to use `super().__init__` in the model runner
Closes #19
=> [V1] Cleanup kv-caching apis and disable paged attention

vllm_spyre/model_executor/model_loader/spyre.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/worker/spyre_model_runner.py
changes:
- moved model loading from `SpyreCausalLM` to `FmsModelWrapper`
=> FMS wrapper model loading

tests/test_spyre_basic.py, vllm_spyre/platform.py, vllm_spyre/v1/core/scheduler.py, vllm_spyre/v1/worker/spyre_model_runner.py
@wallashss related to https://github.com/vllm-project/vllm-spyre/pull/24/files#r2001886143
This fixes an issue where requests could not finish out of order in a batch in the v1 model runner. The request indices need to be remapped to the un-padded output tensors so that the engine knows which output does with which request. Before this change, if the first request in a batch finished before any others, the v1 engine would index past the end of the tensor.
This _also_ addresses a small issue where the v1 scheduler actually seems to need at least 2 blocks for each sequence. I haven't looked into why exactly this is, but without this change it seems that we can only schedule at most half of a full batch. I added some debug logs to the SpyreScheduler so you can see how many requests it passes …
=> :bug: fix batch handling in V1 runner

examples/offline_inference_spyre_cb.py, vllm_spyre/envs.py, vllm_spyre/model_executor/model_loader/spyre.py
changes: 
- introducing env var `VLLM_SPYRE_USE_CB` to switch between continuous batching and static batching
- introducing `FmsModelPseudoWrapper` which mimics the static batching kv cache handling alongside the existing `FmsModelWrapper` for continuous batching kv cache handling
- both wrapper classes inherit from a base class `FmsModelBaseWrapper` to avoid code duplication.
=> FMS Wrapper for static batching

.github/workflows/test-spyre.yml, Dockerfile.spyre, vllm_spyre/v1/core/scheduler.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
This PR implements plugin-side rejection of requests that don't fit a warmup shape
Closes #16 
The reason I did it this way instead of opening an upstream PR for vllm to allow the scheduler to reject requests is:
- There's an open PR (https://github.com/vllm-project/vllm/pull/11737 and https://github.com/vllm-project/vllm/pull/14048) that should allow us to actually raise an error from `add_request` so that the user gets a real 400-type error, which IMHO would be much better than a 200 with empty text
- We're accumulating a lot of drift with the v1 implementation, and I'd prefer us getting a fix in the plugin now rather than waiting on upstream reviews for a feature that the stock v1 scheduler doesn't support, so that we can resume testing against vllm main (or at least the latest …
=> ✨  Reject requests, and upgrade vllm install to 0.8.0

vllm_spyre/platform.py
Adds the new `supports_v1` platform api added upstream here: https://github.com/vllm-project/vllm/pull/15417
This removes one more blocker to moving past vllm v0.8.0
=> :sparkles: re-enable v1

vllm_spyre/core/scheduler.py, vllm_spyre/platform.py, vllm_spyre/v1/core/scheduler.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py, vllm_spyre/worker/spyre_model_runner.py, vllm_spyre/worker/spyre_worker.py
I need to do a demo using V0 online serving today, and I noticed that it is currently not working using latest `aiu-vllm-dev` image:
Trying to deploy the following:
```
python3 -m vllm.entrypoints.openai.api_server --model /models/llama-194m/ --max-model-len=2048 --block-size=128
```
produces:
```
[SpyreWorker] load model...
ERROR 03-25 09:16:21 [engine.py:448] type object 'SpyrePlatform' has no attribute 'spyre_warmup_shapes'
ERROR 03-25 09:16:21 [engine.py:448] Traceback (most recent call last):
ERROR 03-25 09:16:21 [engine.py:448]   File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
ERROR 03-25 09:16:21 [engine.py:448]     engine = MQLLMEngine.from_vllm_config(
ERROR 03-25 09:16:21 [engine.py:448] …
```
=> Ensure that warmup shapes are available after forking.

vllm_spyre/v1/core/sched/output.py, vllm_spyre/v1/core/scheduler.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
Fix #45 
I created a new file that we can import the needed classes from vllm and it solves depending the installed version (for backward compatibility). 
I also did some changes that are only related to TYPE_CHECKING
=> [V1] Fix importings for schedule repackaging

tests/spyre_util.py, tests/test_spyre_online_multi.py
Adds an online TP case - closes #57.
=> Add tensor parallel tests for online server

tests/test_spyre_max_prompt_length.py
[Issue 29](https://github.com/vllm-project/vllm-spyre/issues/29) presents a bug where a specific item in a test was working in V0 and stopped working in V1. 
Currently it seams to be fixed since all tests passed when using V1 and one timeout occurred when using V0. The item that got a timeout passes the test when it is run alone.
I ran the tests using the following commands:
v0: `python -m pytest --timeout=300  tests -v -k "V0 and eager"` 
v1: `python -m pytest --forked --timeout=300  tests -v -k "V1- and eager"`
Item that got a timeout:
`python -m pytest --forked tests -v -k tests/test_spyre_tensor_parallel.py::test_output[V0-eager-2-warmup_shapes0-prompts0-/models/llama-194m]
`
I also run the test using:
`pytest -v -s --forked tests/test_spyre_max_prompt_length.py`
In this last the only …
=> Enable V1 in test_spyre_max_prompt_length

requirements.txt, vllm_spyre/model_executor/model_loader/spyre.py
closes #42 
changes:
- fix import in model loader ([here](https://github.com/vllm-project/vllm-spyre/commit/5773b735a433a2477ec9dd85c001e60b57490b31))
Tested successfully on AIU Spyre with granite 8b.
=> [GPTQ] fix imports of moved add ons 

vllm_spyre/core/scheduler.py, vllm_spyre/v1/core/scheduler.py, vllm_spyre/worker/spyre_model_runner.py
Some fixes from testing handling of request cancellation:
- in V0, guard against a KeyError in `_req_ids2idx`
- in v1, specialize the Scheduler's `finish_requests()` to handle the holdback_queue
FIX https://github.com/vllm-project/vllm-spyre/issues/36
=> [Bugfix][V0][V1] Fix crashes from cancelling requests

.github/workflows/test-spyre.yml, pyproject.toml
Changes:
- Install Python package on GH action runner instead of building Docker image
- Use uv instead of pip as package manager
- Use matrix to test against different build targets
- Use matrix strategy to run v0 and v1 tests in parallel
Resolves #41
---
**TODO:**
- Remove <code>test-spyre</code>
- Add `Test/V0 (vLLM:0.8.3)`, `Test/V1 (vLLM:0.8.3)`
- Leave off `Test/V0 (vLLM:main)`, `Test/V1 (vLLM:main)` as a required check
=> [CI] Test against vllm/main

pyproject.toml, tests/e2e/test_spyre_basic.py, tests/e2e/test_spyre_embeddings.py, tests/e2e/test_spyre_max_new_tokens.py, tests/e2e/test_spyre_max_prompt_length.py, tests/e2e/test_spyre_seed.py, tests/e2e/test_spyre_tensor_parallel.py, tests/e2e/test_spyre_warmup_shapes.py, tests/spyre_util.py, vllm_spyre/core/scheduler.py, vllm_spyre/envs.py, vllm_spyre/v1/core/scheduler.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py, vllm_spyre/worker/spyre_embedding_model_runner.py, vllm_spyre/worker/spyre_model_runner.py, vllm_spyre/worker/spyre_worker.py
This PR adds `requires-python` to the project table in our pyproject.toml. This tells installers what versions of python we support, which is good practice to include when publishing a package. Currently python 3.9 is the oldest version of python that has official support, it will reach end of life this October: https://devguide.python.org/versions/. This plugin shouldn't have any code that specifically prohibits installing with future python versions, so this sets the valid python version range to 3.9+.
As of python 3.9, type hinting with primitive container types (list, dict, tuple) became supported and type hinting with the types from the `typing` package was deprecated. This causes `ruff` to now fail, as we won't support any versions of python that require the older style type hints. …
=> Add `requires-python` and update type hints

pyproject.toml, uv.lock
Updates vLLM to the latest 0.8.4 for our default install configuration
=> :arrow_up: bump vllm to 0.8.4

pyproject.toml
Our builds against fms-mo@main are failing now because fms-mo doesn't support python 3.9 and `uv sync` attempts to find a solution for all python versions we support, which includes python 3.9. After reading the literature, it seems like the solution is _not_ to mark 3.9 as unsupported by our library, but rather just configure uv to not try to solve for python 3.9.
This change fixes the uv sync error:
```
% uv add git+https://github.com/foundation-model-stack/fms-model-optimizer.git@main
Updated https://github.com/foundation-model-stack/fms-model-optimizer.git (acbff2df0703919fceeb4c63776c747a43d08898)
× No solution found when resolving dependencies for split (python_full_version == '3.9.*' and platform_machine == 'arm64' and sys_platform == 'darwin'):
╰─▶ Because the requested Python …
```
=> :bug: fixup installs for future fms-mo versions

tests/e2e/test_spyre_warmup_shapes.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
Closes #20 
This pulls over some code from https://github.com/foundation-model-stack/aiu-fms-testing-utils/pull/13 that properly marks tensors as static/dynamic for prefill and decode when doing static batching. I've tested on a spyre card and confirmed that I can compile multiple warmup shapes (with batch sizes > 1) and run batches of requests
=> :bug: Fix static batching with multiple shapes

vllm_spyre/model_executor/model_loader/spyre.py
This fixes tensor parallelism error when using the new FMS API by adapting the tensor shape of `self.past_key_value_states` using the built-in function `get_num_kv_heads` of vLLM. 
* Closes #99
=> [CB] Fix Tensor Parallelism Error

tests/e2e/test_spyre_static_batching_limits.py
We don't have v0 support for multiple warmup shapes on spyre cards, so this removes v0 from the static batching tests
=> :fire: remove v0 from static batching test

vllm_spyre/model_executor/model_loader/spyre.py, vllm_spyre/v1/worker/spyre_model_runner.py
Two small changes:
- @yannicks1 is right that `model_input.input_masks, 1` is always gonna be size 1, so we don't have to mark it dynamic in the decode passes on warmup
- Marking dimension 2 of each `past_key_value_states` tensor as dynamic only needs to be done at warmup time, we don't need to do it on every forward pass
=> :zap: consolidate tensor marking for static batch runner

vllm_spyre/v1/worker/spyre_model_runner.py
Following up on https://github.com/vllm-project/vllm-spyre/pull/110#discussion_r2059737772 because sometimes my reading comprehension is less than stellar
=> :fire: remove dynamic mark on input_tokens[1]

.github/workflows/test-spyre.yml, pyproject.toml, tests/conftest.py, tests/e2e/test_spyre_basic.py, tests/e2e/test_spyre_embeddings.py, tests/e2e/test_spyre_max_new_tokens.py, tests/e2e/test_spyre_online.py, tests/e2e/test_spyre_online_multi.py, tests/e2e/test_spyre_seed.py, tests/e2e/test_spyre_static_batching_limits.py, tests/e2e/test_spyre_tensor_parallel.py, tests/e2e/test_spyre_warmup_shapes.py, tests/spyre_util.py, tests/utils/test_model_list.py, tests/utils/test_spyre_backend_list.py, tests/utils/test_spyre_model_list.py, tests/v1/worker/test_spyre_input_batch.py
- Updates `get_spyre_model_list()` and `get_spyre_backend_list()` to return a list of pytest parameters with markers (instead of simple strings)
- Pulls out util function into its own directory
- Dynamically mark all tests in `tests/e2e` as `e2e`, manually marked multi-card tests as `multi`, converted versions (v0/v1) to markers, etc.
- Replaces (unused, I think) markers in `pyproject.toml` with new ones such as `v0`, `v1`, `e2e`, `spyre`, `cpu`, `multi`, `quantized`, 
- Remove "eager" backend parameters from multi-card tests
Some examples:
`-m "v0 and cpu and e2e"` to return all e2e-marked tests only with the `eager` backend and `v0` version, this would exclude multi-card tests
`-m "embedding"` to return only embedding model tests
`-m "decoder and spyre"` excludes embedding model tests, …
=> [Tests] Setup pytest markers

examples/offline_inference_spyre_cb_test.py, vllm_spyre/model_executor/model_loader/spyre.py, vllm_spyre/platform.py, vllm_spyre/v1/core/scheduler.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
- Introducing base class `SpyreScheduler` and inherit from it to have a decoupled `StaticBatchingSpyreScheduler` and `ContinuousBatchingSpyreScheduler`
- ensuring warmup shapes are only consumed in the static batching path
- remove static batching warmup envs from `offline_inference_spyre_cb_test.py` (without having it failing:)
- allocate meaningful dynamo cache for continuous batching
closes #98
=> [V1] Decoupling static and continuous batching 

vllm_spyre/v1/core/scheduler.py
These changes from testing request cancellation with the continuous batching branch. In some cases, the cancellation would result in a crash:
```
ERROR 04-25 16:39:23 [core.py:387] EngineCore hit an exception: Traceback (most recent call last):
ERROR 04-25 16:39:23 [core.py:387]   File "/home/senuser/my-vllm/lib64/python3.11/site-packages/vllm/v1/engine/core.py", line 380, in run_engine_core
ERROR 04-25 16:39:23 [core.py:387]     engine_core.run_busy_loop()
ERROR 04-25 16:39:23 [core.py:387]   File "/home/senuser/my-vllm/lib64/python3.11/site-packages/vllm/v1/engine/core.py", line 400, in run_busy_loop
ERROR 04-25 16:39:23 [core.py:387]     self._process_input_queue()
ERROR 04-25 16:39:23 [core.py:387]   File "/home/senuser/my-vllm/lib64/python3.11/site-packages/vllm/v1/engine/core.py", …
```
=> fix/refactor: remove last_running and total_running

tests/conftest.py
Currently, when running tests with `VLLM_USE_V1=1` set in the shell results in all v0 tests failing with the error:
```
self = <vllm.v1.engine.llm_engine.LLMEngine object at 0x7f3b23c5ad90>
vllm_config = VllmConfig(model_config=<vllm.config.ModelConfig object at 0x7f3b23c5a350>, cache_config=<vllm.config.CacheConfig obje...,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, kv_transfer_config=None, additional_config=None, instance_id='f6f6e')
executor_class = <class 'vllm.v1.executor.abstract.UniProcExecutor'>, log_stats = False
usage_context = <UsageContext.LLM_CLASS: 'LLM_CLASS'>, stat_loggers = None
mm_registry = <vllm.multimodal.registry.MultiModalRegistry object at 0x7f3b89bf92d0>, use_cached_outputs = False
multiprocess_mode = True
def __init__(
self,
vllm_config: VllmConfig, …
```
=> :bug: ignore V1 environment setting when testing

tests/v1/worker/test_spyre_input_batch.py, vllm_spyre/core/scheduler.py, vllm_spyre/v1/compat/__init__.py, vllm_spyre/v1/compat/output.py, vllm_spyre/v1/worker/spyre_input_batch.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
Updates to get vllm-spyre working with vLLM `main` after some recent changes.
For V1, the optional `prompt` field was removed from some ouptut classes in vLLM. Since these were optional anyways (and just used in our warmup requests), there isn't any backwards compatibility issue.
https://github.com/vllm-project/vllm/pull/17214/files#diff-cafd89ce8a698a56acb24ada62831cbc7a980782f78a52d1742ba238031f296cL25
For V0, mulitmodal input processing has gone through an overhaul, the part that matters here is the removal of `mm_processor_kwargs` from `SequenceGroup`. This field was also optional before it was removed.
https://github.com/vllm-project/vllm/pull/15686/files#diff-0e64e07127ff20fc01be18cc95c0f58e0ff818e0dbabd5e8d2e07ca27943a7e4L1599
FIX …
=> Fixes to get things working with upstream main

.github/workflows/publish-to-test-pypi.yaml
Currently the publications on main to test pypi are broken, because the job doesn't checkout the main branch history to calculate the correct semantic version to push based on the last tag. This fixes that, so we should have green deployments to test pypi again, and for any failures we can investigate the actual packaging failure.
Here's a test run of the changes: https://github.com/vllm-project/vllm-spyre/actions/runs/14892371588/job/41827331149
=> Fix test pypi publications

vllm_spyre/v1/worker/spyre_model_runner.py
since upstream PR introduced a default param in `ModelRunnerOutput`
https://github.com/vllm-project/vllm/pull/17751/files#diff-267e8bc1629d4ae978c28eea04881c9934449a35c1f74c6214636f213bde8ccdR104-R105
=> 🐛 set default value for tkv

vllm_spyre/model_executor/model_loader/spyre.py
We need to pass additional options to torch.compile to ensure that symbols get added to the graph.
=> Add options to torch.compile

tests/e2e/test_spyre_warmup_shapes.py
This PR mark the current tests that are currently failing when compile cache is enabled. It will allow to run the CI/CD pipeline with compile cache, while filtering out the tests that fail. 
Goes along with [this PR](https://github.ibm.com/ai-foundation/aiu-tests/pull/257)
=> [CI/CD] mark current tests that are failing when compile cache is enabled

tests/e2e/test_spyre_warmup_shapes.py
Disable compile cache in `test_spyre_warmup_shapes` because this test fails with cache enabled. Need to debug
=> Disable compile cache in test_spyre_warmup_shapes

tools/shellcheck.sh
Allowing the `shellcheck` command to run against all shell script files within `.venv` gives the error: 
```
xargs: command line cannot be assembled, too long
```
This PR only checks the shell scripts that are git committed.
After ignoring:
```
❯ git ls-files -z | grep -z '\.sh$' | xargs -0 -n 1 printf "%s\n"
format.sh
tools/actionlint.sh
tools/check_repo.sh
tools/doc-lint.sh
tools/mypy.sh
tools/shellcheck.sh
```
Before:
```
❯ find . -name "*.sh"
./tools/shellcheck.sh
./tools/doc-lint.sh
./tools/check_repo.sh
./tools/actionlint.sh
./tools/mypy.sh
./.venv/lib/python3.12/site-packages/bleach/_vendor/vendor_install.sh
./.venv/lib/python3.12/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/linux_and_mac/compile_mac.sh
./.venv/lib/python3.12/site-packages/debugpy/_vendored/pydevd …
```
=> 🐛 ignore shell script files within .venv for shellcheck command

tests/e2e/test_spyre_warmup_shapes.py
Disabling caching from within the test doesn't work when running multiple tests. So reverting to skipping the failing test with cache.
=> Revert commit (disabling caching in test doesn't work)

docs/source/contributing/overview.md, pyproject.toml
- Adds information about opening issues/bug reports, PR linting, etc. and point to Slack support
- Remove debugpy doc because it doesn't seem vllm-spyre related (same example [here](https://code.visualstudio.com/docs/python/debugging#_example))
- Copy-edit testing docs
=> [Docs] Update contributing docs

pyproject.toml, tests/e2e/test_spyre_cb.py
Update vllm dependency to >=v0.9.0, this allows to cleanup some code that was required to maintain compatibility with older vllm version.
=> Update vllm dependency to >=v0.9.0

tests/e2e/test_spyre_cb.py
`data_parallel_rank` added to `EngineCoreRequest`
=> 🐛 fix for upstream change

tests/conftest.py, tests/e2e/test_spyre_online.py, tests/e2e/test_spyre_online_multi.py, tests/e2e/test_spyre_tensor_parallel.py, tests/spyre_util.py
This PR adds more TP sizes to the tests marked `multi`, and skips them if the required cards are not available
=> :white_check_mark: add more TP sizes to tests

tests/e2e/test_spyre_basic.py, vllm_spyre/platform.py
This fixes an issue where batches of requests with long prompts would not properly be scheduled. Even with a long queue of requests, smaller-than-full batches would be scheduled because requests would be rejected from the schedule once the total number of prompt tokens was >= `--max-num-batched-tokens`.
The `--max-num-batched-tokens` config is designed for chunking up prompts for chunked prefill, and isn't relevant for static batching. This PR sets `--max-num-batched-tokens` to the maximum number of prompt tokens that could be in a full batch, so that the chunked prefill logic doesn't prevent us from creating large batches.
I missed this before because it requires a lower level test that invokes the scheduler directly in order to ensure that the full batches are actually scheduled.
=> :bug: fix static scheduling issues with long prompts

docker/Dockerfile.amd64
Missed this on internal testing for 0.3.0 with TP support :(
These modules are required to be ignored for graph compilation to function in tensor parallel mode
=> :bug: add required ignore modules for tensor parallel

.github/workflows/test.yml
Currently, the tests workflow runs on every PR but skips actually running the install and test steps when no source code was changed (PR #193) in order to complete PR checks more quickly and preserve GHA minutes, while allowing tests to be required PR check.
However, as witnessed in PR #213, https://github.com/vllm-project/vllm-spyre/actions/runs/15474000691/job/43565048121, tests don't run when only Python package versions are updated.
This PR changes that. Running full tests on `uv.lock` updates.
=> [CI] Don't skip tests when `uv.lock` is updated

.github/workflows/type_check.yaml
**TODO**: 
- [repo admin] After merge, remove required PR check `type-check (3.9)`
> error: The current Python platform is not compatible with the lockfile's supported environments: `python_full_version >= '3.10'`
=> [CI] Use `uv` for type-check

.github/workflows/build_docker.yml
The `Build Docker` workflow is one of the biggest consumers of Github Action minutes.
To preserve our GHA quota, only run Docker image build on PRs that change relevant files:
- `.github/workflows/build_docker.yml`
- `docker/**`
- `vllm_spyre/**/*.py`
- `pyproject.toml`
- `uv.lock`
=> [CI] Only build docker image on source changes

pyproject.toml, uv.lock
vLLM v0.9.1 contains a bug that causes vllm-spyre to hang on boot-up.
The bug is not respecting `num_gpu_blocks_overrides`. It was introduced in https://github.com/vllm-project/vllm/pull/17996 and fixed in https://github.com/vllm-project/vllm/pull/19503.
=> Exclude vllm v0.9.1 as an allowed version due to breaking bug

tests/e2e/test_spyre_warmup_shapes.py, vllm_spyre/model_executor/model_loader/spyre.py, vllm_spyre/v1/worker/spyre_model_runner.py
We were having problems with pytest-forked and cache. After some investigation and debugging I figure it out that we were importing torch_sendnn before it was necessary, so pytest already initialize the runtime and the forking inherit it, which I believe it was the cause of the problems with the cache.
Also I re-enabled a test that was skipped because of this known issue.
Potentially fix: #150
=> [FIX] lazy import of SpyreCausalLM to avoid issues with pytest-forked

vllm_spyre/platform.py
Earlier, the error showed up as
```
RuntimeError: Warmup shape [4, {shape['prompt_length']}, {shape['new_tokens']}] results in a maximum sequence length of {max_seq_len} which is longer that what the model supports ({max_model_len})
```
After this fix, it shows up correctly:
```
RuntimeError: Warmup shape [4, 128, 20] results in a maximum sequence length of 148 which is longer that what the model supports (128)
```
=> 🐛 fix runtime msg

vllm_spyre/v1/worker/spyre_worker.py
This changes the warmup for static batching back to how it originally was, only warming up a single pass.
This fixes a bug where the compiled model graphs were incorrect- we would invoke the model with one batch size and the model would output a different batch size.
=> :bug: fixed static batch warmup

pyproject.toml, tests/e2e/test_spyre_async_llm.py, uv.lock, vllm_spyre/v1/worker/spyre_model_runner.py
FIX https://github.com/vllm-project/vllm-spyre/issues/225
=> fix: avoid KeyError when cancelling requests that have not been processed

tests/conftest.py, tests/e2e/test_spyre_basic.py, tests/e2e/test_spyre_cb.py, tests/spyre_util.py
- ✅ change `max_model_len` to `256`
- ✅ edit HF test description
- ✅add `pytest.xfail` for failing CB tests
- ✅ run batch handling test for CB too
- Fix https://github.com/vllm-project/vllm-spyre/issues/256
=> ✅ CB tests refactoring + adding batch test

docs/contributing/README.md, examples/offline_inference/cb_spyre_inference.py
`paged_attn_mock` branch of fms is no longer needed and API on `main` supports both, static and continuous batching simultaneously #162
=> [CB] remove reference to outdated fms feature branch

vllm_spyre/v1/worker/spyre_model_runner.py
=> [CB] use used block ids for dummy batch size 2

docs/contributing/README.md
=> [Docs] Remove xgrammar install step

vllm_spyre/__init__.py
vLLM has mechanism to change [logging configuration](https://docs.vllm.ai/en/v0.7.2/getting_started/examples/logging_configuration.html) by using environment variables.  However, vllm_spyre does not refers to these environment variables, but it always configure python logging based on the hard coded default of vLLM.  As a result, changing logging configuration results in mixing log messages of different configurations and generates inconsistent logs.
This PR updates initialization of python logger in vllm_spyer to respect the logging configs and use the same logging configuration as vllm.
=> Respect vllm logging configs in vllm_spyre

vllm_spyre/v1/worker/spyre_worker.py
This came out of a follow up to https://github.com/vllm-project/vllm-spyre/pull/270 to determine why an extra Prefill was necessary after using `warmup_mode`. I learned that the extra Prefill is required to deploy the compiled graph to the Spyre device. This PR does not change any functionality, but updates logging and documentation around warmup to make this clearer.
=> Update warmup log messages and comments

tests/e2e/test_spyre_max_new_tokens.py
Add cb parameterization to `tests/e2e/test_spyre_max_new_tokens.py`
=> [tests] add cb parameterization

vllm_spyre/v1/worker/spyre_worker.py
Fixes a bug introduced in #283 where the decode pass was moved out of the warmup context.
AKA: @prashantgupta24's editor likes to unindent things, and @joerunde likes to view diffs with whitespace changes ignored, so here we are 😅
=> :bug: put decode back in warmup

docker/Dockerfile.amd64
Bumps the base image to the latest tag that's been verified and pushed to quay
=> :arrow_up: bump base image

pyproject.toml, uv.lock
Adds `pytest-forked` back as a dev dependency. We still need it to reliably run tests on spyre hardware due to segfaults crashing the entire test suite
=> :bug: add pytest-forked dev dep back

.github/workflows/test.yml, vllm_spyre/platform.py
Closes #305 
The changes in upstream that are breaking tests with vLLM:main branch are twofolds:
1. [This PR](https://github.com/vllm-project/vllm/pull/20061) introduces[ an import](https://github.com/vllm-project/vllm/blob/8020e98c9f033e76c97eb8261f772d59eba49c9a/vllm/model_executor/model_loader/bitsandbytes_loader.py#L23) which is incompatible with torch 2.5.1
2. Previously, when `model_config.task` was set to `auto`, the task could be automatically resolved in vLLM: after the post-init method of `ModelConfig`, the `task` field was automatically replaced from `auto` to .e.g. `generate` or `embed`). With the changes in [This PR](https://github.com/vllm-project/vllm/commit/020f58abcdea65302225663130d08fd8f4dd755a), the task in `model_config`, cannot be automatically resolved anymore when …
=> [Fix] Tests breaking with vLLM:Main

tests/e2e/test_spyre_basic.py, tests/e2e/test_spyre_cb.py
Re-enabling `VLLM_ENABLE_V1_MULTIPROCESSING` because it interferes with tests concurrency.
=> remove `VLLM_ENABLE_V1_MULTIPROCESSING` disabling

vllm_spyre/model_executor/model_loader/spyre.py
@JRosenkranz says this should be sdpa_causal, but it doesn't matter since we always pass a mask
=> :bug: use right attention name

.github/workflows/test.yml, tests/e2e/test_spyre_prompt_logprobs.py, tests/e2e/test_spyre_static_batching_limits.py, tests/spyre_util.py
~~Testing whether or not torch 2.7 will cause the EADDRINUSE failures on vllm 0.9.2~~
Edit: The issue appears to be with the shutdown logic in vllm, with TP running the model executor is not shut down when an `LLM` is garbage collected. This is caused by a circular reference in vllm.executor.ray_utils when ray is not installed. This PR adds a temporary workaround to force the engine shutdowns after each test.
Also updating to torch 2.7.1 everywhere since our next release will have 2.7.1 in the base image as well.
=> :bug: Workaround ray issue in tests

tests/conftest.py
`--tensor-parallel-size` and `tp_size` flag being used regardless of the the block checking if `tp_size` exists.
=> [Fix][Tests] TP param used in tests unconditionally

vllm_spyre/v1/worker/spyre_worker.py
This PR adds assertions for operations done within the `warmup context`. Earlier we saw a bug in which the `decode` warmup was moved outside the warmup context because of one simple indentation issue and it caused a segmentation fault with no clue as to why it was happening.
These assertions should catch the error when running even on CPU.
=> ✅ add assertions for warmup mode context

tests/e2e/test_spyre_basic.py, vllm_spyre/v1/worker/spyre_worker.py, vllm_spyre/worker/spyre_worker.py
this is relaxing an old constraint on the number of requested new tokens having to be a min of 3. Turns out it is only important that during the warmup there is at least **one** decode forward pass. Requesting 1 token runs prefill only during warmup -> compiler crashes (I guess it is expecting two graphs, prefill and decode) . Requesting 2+ tokens does at least one decode during warmup and thus produces a decode graph too -> things run smoothly for 2+ tokens ...
=> [SB] relax constraint on min number of new tokens

examples/offline_inference/long_context.py, vllm_spyre/platform.py
Prefill already provides one new token (without requiring any KV cache for it). 
Example: for max model length 2048 it is possible to do a prefill on a prompt of size 2048 to (32 blocks in Spyre) when only requesting 1 token. A 33rd block is only needed if a 2nd output token was requested and that would violate the max model length. 
changes:
- correct assertion in platform.py: allow any requests that satisfy: `prompt_padding_len + max_tokens - 1 <= max_model_len`
- correct long_context.py: allowing `prompt_len <= max_model_len` while setting 
`new_tokens = max_model_len + 1 - prompt_padding_len`
=> [CB] bug fix: account for prefill token 

tests/e2e/test_spyre_cb.py
This adds a failing test case for handling batch size 4 at 4k context length with continuous batching.
This tests the `eager` backend against the `sendnn` backend, which is currently failing on `quay.io/ibm-aiu/spyre-base:2025_07_18-amd64`
=> :test_tube: add long context test

.github/workflows/lint_docs.yml, docs/.nav.yml, docs/contributing/continuous_batching/overview.md, docs/getting_started/installation.md, pyproject.toml
Update the install docs to include install from PyPI
https://vllm-spyre--327.org.readthedocs.build/en/327/getting_started/installation.html#install-vllm-with-the-vllm-spyre-plugin
=> [docs] Add install from PyPI to docs

tests/scheduling_utils.py, vllm_spyre/envs.py, vllm_spyre/model_executor/model_loader/spyre.py, vllm_spyre/platform.py, vllm_spyre/v1/worker/spyre_model_runner.py
depreciating the env var `VLLM_SPYRE_N_BLOCKS` and use the top level argument `num_gpu_blocks_override` instead to override the number of avail spyre kv cache blocks.
=> [CB] Override number of Spyre blocks: replace env var with top level argument

vllm_spyre/core/scheduler.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py, vllm_spyre/worker/spyre_embedding_model_runner.py
- Remove prompt adapter config
- Based on upstream vllm changes in https://github.com/vllm-project/vllm/pull/20588
- Implement `get_supported_tasks` in model_runner for online API
-  only needed for online API, related PR - https://github.com/vllm-project/vllm/pull/21585
Implementation for online API:
```
if envs.VLLM_USE_V1:
supported_tasks = await engine_client \
.get_supported_tasks()  # type: ignore
else:
supported_tasks = model_config.supported_tasks
```
fix https://github.com/vllm-project/vllm-spyre/issues/336
=> ♻️ Compatibility with vllm main

tests/e2e/test_spyre_cb.py
Add tests to check if the API is generating the correct amount of tokens when CB is enabled.
=> Add CB API tests on the correct use of max_tokens 

vllm_spyre/platform.py, vllm_spyre/v1/worker/spyre_worker.py, vllm_spyre/worker/spyre_worker.py
It seems `model_config.task` is deprecated, instead from what I understand we can use `model_config.supported_tasks`, which is initialized when an llm engine is instantiated:
https://github.com/vllm-project/vllm/pull/21470/files#diff-7eaad0b7dee0626bf29d10081b0f0c5e3ea15a4af97e7b182a4e0d35f8346953R705-R706
To maintain backward compatibility, it's a bit tricky since:
- Earlier version had `model_config.task` pointing to the task and `model_config.supported_tasks` as a list of all tasks which could contain more than 1 task
```
model_config.task :  generate
model_config.supported_tasks :  {'embed', 'reward', 'generate', 'classify'}
``` 
- Latest `main` now populates `model_config.supported_tasks` as the only task the model supports.
```
model_config.task :  None
model_config.supported_tasks …
```
=> ♻️ fix vllm:main

.github/workflows/test.yml, tests/e2e/test_spyre_prompt_logprobs.py
We should be able to run the tests in offline mode to avoid multiple calls to HF unnecessarily.
This also caught a bug (I think?) in one of the tests where we were unnecessarily trying to download the `facebook/opt-125m` model.
=> ♻️ enable offline mode in GHA tests

docs/contributing/continuous_batching/tests/scheduler_steps_tests.md
we now do assert output correctness for the scheduling test since #337 , hence this warning should be removed.
=> [docs][CB] remove warning that no output correctness is asserted for scheduler step tests

tests/utils/test_upstream_compatibility.py, vllm_spyre/v1/worker/spyre_model_runner.py
parameters `default_normalize` and `default_softmax` are deprecated
=> [embedding] support newest vllm main branch 

vllm_spyre/v1/worker/spyre_model_runner.py
We have received a number from the compiler team for the [model](https://huggingface.co/ibm-granite/granite-3.3-8b-instruct) of interest with TP 4 and hard code it here. For all other models/ TP sizes the number of blocks defaults to `max_batch_size * max_model_len / block_size`.
=> [CB] hard code number of spyre blocks to 2080

vllm_spyre/platform.py, vllm_spyre/v1/core/scheduler.py
[CB] set and respect compiler constraint VLLM_DT_MAX_BATCH_TKV_LIMIT
The Spyre compiler has a constraint on the product of the batch size and tkv. For our [reference model](https://huggingface.co/ibm-granite/granite-3.3-8b-instruct) and TP=4 it cannot exceed `VLLM_DT_MAX_BATCH_TKV_LIMIT=131072`. The default value for all other models/ TP sizes is `VLLM_DT_MAX_BATCH_TKV_LIMIT=max_model_len * max_batch_size
`
changes:
- set `VLLM_DT_MAX_BATCH_TKV_LIMIT` depending on model and TP size
- introduce additional scheduler condition respecting this new constraint
- add drawing explaining the new scheduler check [here](https://github.com/vllm-project/vllm-spyre/pull/363#issuecomment-3173605517)
=> [CB] set and respect compiler constraint VLLM_DT_MAX_BATCH_TKV_LIMIT 

vllm_spyre/model_executor/model_loader/spyre.py
Otherwise the lines are spaced out weird
```DEBUG 08-12 20:14:35 [spyre.py:261] You are casting param base_model.layers.14.attn.in_proj.key.weight to fp16, which                         will cause loss of accuracy. You can ignore                             this warning if this is intended.```
=> 🎨 fix warning logs for _cast_bf16_to_f16

tests/utils/test_upstream_compatibility.py, vllm_spyre/platform.py, vllm_spyre/v1/worker/spyre_model_runner.py
Adds compatibility code for the `default_pooling_type` argument that was removed
https://github.com/vllm-project/vllm-spyre/issues/371
=> Add compat code for changing Pooler function signature

README.md
Add link in README to indicate POWER is a supported architecture.
=> Document support for POWER architecture in README

vllm_spyre/model_executor/model_loader/spyre.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
Currently, the number of blocks (in particular the kv cache tensor shape) has to be consistent across warmup and inference. PR #362 introduced inconsistency which led to recompilation for a certain model/TP combination. 
This PR fixes above and refactors the warmup to make it more readable.
=> [high prio][CB] 🐛 fix warmup

.github/workflows/test.yml
previously PR #388 did only respect manually added `ready` labels. This PR extends the triggering the test against vLLM:main for `ready` labels added by the bot (by enabling auto-merge).
=> [GHA] Triggering test agains vLLM:main for ready labels added by bot

.github/workflows/test.yml
Since #393 , we only load a subset of the cached models instead of all. However, the condition in "Save HF models cache" assumed that all caches across the matrix are the same (as previously the case) and only saved the one for the first job. I removed that condition to save in all cases.
=> [GHA] 🐛 fix: Save HF models cache for all jobs

tests/e2e/test_spyre_cb_scheduler_steps.py
changes:
- number of available blocks was missing (note we don't state it if set to 1000 (no restriction)
- number of available blocks was stated wrongly (8 instead of 4)
=> [test] 🎨 fix test description string

tests/aftu/test_compare_graphs.py, tests/conftest.py, tests/e2e/test_spyre_async_llm.py, tests/e2e/test_spyre_basic.py, tests/e2e/test_spyre_cb.py, tests/e2e/test_spyre_cb_scheduler_steps.py, tests/e2e/test_spyre_embeddings.py, tests/e2e/test_spyre_max_new_tokens.py, tests/e2e/test_spyre_online.py, tests/e2e/test_spyre_prompt_logprobs.py, tests/e2e/test_spyre_seed.py, tests/e2e/test_spyre_stagger_basic.py, tests/e2e/test_spyre_static_batching_limits.py, tests/e2e/test_spyre_warmup_shapes.py, tests/spyre_util.py, tests/utils/test_upstream_compatibility.py
Introduces `pytest_generate_tests` - [pytest_generate_tests](https://docs.pytest.org/en/latest/how-to/parametrize.html#pytest-generate-tests) allows one to define custom parametrization schemes or extensions.
`pytest_generate_tests` is called when collecting a test function. Through the passed in `metafunc` object you can inspect the requesting test context and, most importantly, you can call `metafunc.parametrize()` to cause parametrization.
This was required for full model testing, in which case we want some of the parameters to change based on certain runtime configurations.
Running `pytest -m "full_model and cb"` will inject `full_model` CB arguments into the test marked with `full_model` .
_Note: We make sure to not parametrize something if it exists explicitly on the test._
⚠️ ⚠️ ⚠️ …
=> ♻️ [tests] Full model testing

vllm_spyre/v1/worker/spyre_worker.py
After properly updating the stagger wrapper we forgot to actually assign it back to the warmup mode's exit method. This passes manually on my dev pod and looks like it does stagger the exit of warmup_mode
cc @jberkhahn
=> :bug: fixup compilation wrapper

vllm_spyre/v1/worker/spyre_model_runner.py
@joerunde's request to link my iPad [drawing](https://github.com/vllm-project/vllm-spyre/pull/363#issuecomment-3173605517) explaining the function in #363 in the code, made me think it might be useful to also link the drawings about the other optimizations I made. 
changes: 
- uploaded and linked [this](https://github.com/vllm-project/vllm-spyre/pull/131#issuecomment-3233440852) drawing explaining #131
- linked [this](https://github.com/vllm-project/vllm-spyre/pull/340#issuecomment-3179337304) drawing (page 3) explaining  #340 
- linked the [same](https://github.com/vllm-project/vllm-spyre/pull/340#issuecomment-3179337304) drawing (page 2) explaining #262
=> [doc] 👨‍🎨 Adding drawings explaining optimizations 

tests/e2e/test_spyre_cb_scheduler_steps.py
There was a undetected merge conflict of #425 and #428. This PR fixes the conflict in the added tests.
=> 🐛 solve undetected merge conflict with main

.github/workflows/lint_code.yml
As part of the `lint-code` CI check, `isort` will raise errors if import statements are not well organized.
However it does not reveal how to fix them. This change will ensure the corrected imports are visible in the CI logs.
N/A
=> CI: Show isort diff

tools/type_check.sh
Currently, type-check with `mypy` defaults to Python 3.9 which generates incorrect type hint errors and we longer support Python 3.9 (or 3.10)
N/A
=> chore: Use Python 3.11 by default for type-check

.github/workflows/test.yml, pyproject.toml, tests/spyre_util.py, tests/utils/test_upstream_compatibility.py, vllm_spyre/platform.py, vllm_spyre/v1/worker/spyre_input_batch.py, vllm_spyre/v1/worker/spyre_model_runner.py, vllm_spyre/v1/worker/spyre_worker.py
⬆️ bump vllm lower bound to 0.10.1.1 and remove a bunch of backward compatibility code.
Note: This is an intermediate PR for supporting the 0.10.2 since it makes it easy to remove backward compatibility code first before introducing breaking changes for the next release.
=> ⬆️ bump vllm lower bound to 0.10.1.1

vllm_spyre/v1/worker/spyre_model_runner.py
The pooler is always run in in the transformers code even when the outputs aren't used. And in our case, we instantiate the pooler outside of the transformers code to use the vLLM code.  In a small test that I'm using the total time goes from 1.8s to 1.2s,.
=> disable transformers pooler

vllm_spyre/envs.py, vllm_spyre/platform.py
In some environments the default of `inductor` here is breaking vllm where a compiler isn't available.
This PR makes the simple compile backend configurable, and defaults to `eager` for portability.
=> :bug: use eager compile

vllm_spyre/v1/worker/spyre_model_runner.py
When padding the position ids, we should always use 0 (not padding token id !)
As the mask disregards the padded tokens anyway, that does not have an influence on the generation results. It can break the implementation though when the padding token is bigger than the max model length (that is also how I found the bug). 
**_For the models we support so far this was never a problem, but for future ones we should fix it!_**
Note: We did not find that bug earlier as for our models of interest, the padding token id happens to be 0 too, but that does not have to hold true in general.
=> [CB] 🐛  fix padding of position ids

pyproject.toml, uv.lock
Few pakcages are not available for s390x  and usually built by source, skipping those packages from pyproject and executed `uv lock`
=> [s390x] Update s390x depencies

tests/llm_cache.py
this change does always compile for the next power of 2 for the batch size.
=> [fp8] fix cb scheduler step tests

vllm_spyre/envs.py
Updates the default simple compile backend to `inductor` to match vLLM.
This could be considered slightly risky because it updates default behavior, but we do want to run with `inductor` where possible. This was previously set to `eager` because we had issues linking g++ correctly and needed a fast workaround.
Impact here should be minimal. If users run into problems with environments that don't have python headers and a valid compiler toolchain, they can run with `VLLM_SPYRE_SIMPLE_COMPILE_BACKEND=eager`
=> :wrench: Update default simple compile backend

tests/conftest.py, tests/llm_cache_util.py, tests/spyre_util.py
This PR fixes a bug where the test collection failed on the full-sized models because we injected a string instead of a `ModelInfo` for the `model` param. This both:
1. Updates the full-sized model parameterization to use a ModelInfo with a pinned revision
2. Updates the test collection code to not fail if a string is passed anyway
=> :bug: fixup full_model marker

tests/conftest.py, tests/e2e/test_spyre_basic.py, tests/llm_cache.py
Recent updates are causing issues with running granite models @ context length 256. This updates the unit tests to default to 512 instead.
=> :bug: use 512 tokens instead of 256
